branches:
  only:
    - main
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - BUILD_SUFFIX="-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}"

language: go

go:
  - 1.x

cache:
  directories:
    - $GOPATH/pkg/mod

script: make testrace build

jobs:
  include:
    - os: linux
      arch: amd64
      script: make lint testrace build # Only run lint here
    - os: linux
      arch: arm64
    - os: linux
      arch: ppc64le
    - os: linux
      arch: s390x
      script: make test build # -race not supported on s390x
    - os: osx
    - os: windows
      script: choco install make && make testrace build
      env:
        - BIN_SUFFIX=".exe"


deploy:
  provider: releases
  file:
    - bin/*.tar.gz
  edge: true # opt in to dpl v2
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
