branches:
  only:
  - main
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

env:
  global:
    - BUILD_SUFFIX="-${TRAVIS_BRANCH}-${TRAVIS_OS_NAME}-${TRAVIS_CPU_ARCH}"

language: go

os:
  - linux
  - osx

arch:
  - amd64
  - arm64

go:
  - 1.x

deploy:
  provider: releases
  file: bin/*.tar.gz
  edge: true # opt in to dpl v2
  on:
    tags: true

after_success:
  - bash <(curl -s https://codecov.io/bash)
