# This is a trivial configuration that presents a local CockroachDB
# cluster as a unified endpoint.
diagAddr: 127.0.0.1:6060
frontends:
  - backendPool:
      tiers:
        - dialFailureTimeout: 30s
          maxBackendConnections: 32
          targets:
            - hosts:
                - 127.0.0.1
              port: 26258
            - hosts:
                - 127.0.0.1
              port: 26259
            - hosts:
                - 127.0.0.1
              port: 26260
    bindAddress: 127.0.0.1:26257
    idleDuration: 1h
  - backendPool:
      tiers:
        - dialFailureTimeout: 30s
          maxBackendConnections: 0
          targets:
            - hosts:
                - 127.0.0.1
              port: 8081
            - hosts:
                - 127.0.0.1
              port: 8082
        - dialFailureTimeout: 30s
          maxBackendConnections: 0
          targets:
            - hosts:
                - 127.0.0.1
              port: 8083
    bindAddress: 127.0.0.1:8080
    idleDuration: 1h
gracePeriod: 30s