# This is a trivial configuration that presents a geo-distributed
# CockroachDB cluster as a unified endpoint.
diagAddr: :6060
frontends:
  - bindAddress: :26257
    idleDuration: 5m
    backendPool:
      tiers:
        - maxBackendConnections: 256
          forcePromotionAfter: 1m
          targets:
            - hosts:
                # East
                - 10.142.0.3
                - 10.142.0.2
                - 10.142.0.5
                # West
                - 10.138.0.25
                - 10.138.0.23
                - 10.138.0.15
                # Europe
                - 10.154.0.24
                - 10.154.0.39
                - 10.154.0.25
              port: 26257
  - bindAddress: :8080
    idleDuration: 5m
    backendPool:
      tiers:
        - targets:
            - hosts: # East
                # East
                - 10.142.0.3
                - 10.142.0.2
                - 10.142.0.5
                # West
                - 10.138.0.25
                - 10.138.0.23
                - 10.138.0.15
                # Europe
                - 10.154.0.24
                - 10.154.0.39
                - 10.154.0.25
              port: 26258
gracePeriod: 5s