# This is a trivial configuration that presents a geo-distributed
# CockroachDB cluster as a unified endpoint.
diagAddr: :6060
frontends:
  - bindAddress: :26257
    idleDuration: 5m
    backendPool:
      tiers:
        - maxBackendConnections: 256
          targets:
            - hosts: # East
                - 10.142.0.85
                - 10.142.0.89
                - 10.142.0.86
              port: 26257
        - maxBackendConnections: 128
          forcePromotionAfter: 1m
          targets:
            - hosts: # West
                - 10.138.0.12
                - 10.138.0.7
                - 10.138.0.5
              port: 26257
        - maxBackendConnections: 8
          forcePromotionAfter: 15s
          targets:
            - hosts: # Europe
                - 10.154.0.73
                - 10.154.0.75
                - 10.154.0.72
              port: 26257

  - bindAddress: :8080
    idleDuration: 5m
    backendPool:
      tiers:
        - targets:
            - hosts: # East
                - 10.142.0.85
                - 10.142.0.89
                - 10.142.0.86
              port: 26258
        - targets:
            - hosts: # West
                - 10.138.0.12
                - 10.138.0.7
                - 10.138.0.5
              port: 26258
        - targets:
            - hosts: # Europe
                - 10.154.0.73
                - 10.154.0.75
                - 10.154.0.72
              port: 26258
gracePeriod: 5s